### ISSUE TITLE
Bug no cat e vi

### ISSUE THREAD

**Issue by priscilasousa** [halanamelo/infogas02#7]
O bug acontece quando em um mesmo arquivo, eu visualizo com o cat e me mostra um arquivo e abro com o vi para poder editar e me mostra um conteúdo diferente do que mostra quando vejo com o cat.

**Comment by bmhori** [comment]
Ele está desatualizdo, usa o codigo para ler o arquivo e depois da o cat e o vi, estarão iguais.
