### ISSUE TITLE
Como descripitografar arquivo.

### ISSUE THREAD

**Issue by dmfds** [halanamelo/infogas02#8]
Boa tarde grupo, 

Acabei colocando uma senha de acesso no arquivo esquelo.gpt acidentalmente e não estou conseguido retira-lá. Como faço para resolver esse empecilho?

**Comment by priscilasousa** [comment]
Digita ESC :X e na senha, tu coloca ENTER, ENTER aí vai ficar como se tua senha tivesse em branco. Vê se funciona.

**Comment by lucasmgila** [comment]
Da merge do master pro seu feature. Vai perder o que editou, mas pelo menos vai resolver. Depois edita de novo.
PS: Mas só vale a pena se não tiver editado muita coisa.

**Comment by dmfds** [comment]
Valeu pessoal, problema resolvido com sucesso!
